FROM solanalabs/rust:1.55.0

# Set up the working directory
# WORKDIR /app

# Install any additional dependencies
RUN apt-get update && apt-get install -y build-essential

# Copy in any necessary files or scripts
# COPY . /app

# Launch the Anchor CLI when the container starts
# CMD ["anchor"]
ENTRYPOINT ["/bin/bash"]