# Use an official Ubuntu runtime as a parent image
FROM ubuntu:latest

# Set the working directory to /app
WORKDIR /app

# Install required packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y curl git libssl-dev pkg-config

# Set the environment variables
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Install Rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y && \
    rustup component add rust-std --toolchain stable-aarch64-unknown-linux-gnu && \
    rustup target add bpfel-unknown-unknown

# Install Solana
ARG SOLANA_VERSION=1.8.0
RUN curl -sSf https://release.solana.com/v${SOLANA_VERSION}/install | sh -s -- --target ~/solana/ --no-modify-path && \
    echo "source ~/solana/env.sh" >> ~/.bashrc

# Install Anchor
ARG ANCHOR_VERSION=0.26.0
RUN git clone --branch v${ANCHOR_VERSION} https://github.com/project-serum/anchor.git && \
    cd anchor/cli && \
    cargo install --path . --locked --force --features="no-self-update"

# Set the entrypoint to the bash shell
ENTRYPOINT ["/bin/bash"]
