name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - 
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: hieuphq
        password: dckr_pat_3HXheJZ-PfJ_0ynGV_C6tDH3z7o

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: hieuphq/sol-anchor:v0.2

        